#ifndef ERROR_CODE
#define ERROR_CODE

namespace lyrics
{
	enum class ErrorCode: unsigned int
	{
		WRONG_CHARACTER = 2001, STRING_NOT_TERMINATED,
		EXPECTED_RIGHT_PARENTHESIS = 3001, INCOMPLETE_ARRAY_LITERAL, EXPECTED_HASH, INCOMPLETE_HASH_LITERAL, EXPECTED_PRIMARY_EXPRESSION, EXPECTED_INDEX, EXPECTED_FUNCTION_CALL, EXPECTED_MEMBER, EXPECTED_LHS, EXPECTED_VARIABLE_NAME, EXPECTED_PARAMETER_NAME, OUTPUT_PARAMETER_DEFAULT_ARGUMENT, INCOMPLETE_FUNCTION, EXPECTED_PARAMETER, EXPECTED_BASE_CLASS, EXPECTED_CLASS_NAME, EXPECTED_PACKAGE_NAME, EXPECTED_PACKAGE, EXPECTED_END, EXPECTED_END_ELSE_ELSEIF, EXPECTED_WHEN_ELSE_ELSEIF, EXPECTED_WHEN, INCOMPLETE_FOR, INCOMPLETE_FOREACH
	};
}

#endif
